"""from .Administrador import *
from .Alternativa import *
from .Conferencia import *
from .Curso import *
from .Debate import *
from .EsegJNE import *
from .Examen import *
from .ExamenPregunta import *
from .Externo import *
from .Militante import *
from .MilitanteExamen import *
from .PartidoPolitico import *
from .Persona import *
from .PlanEstudio import *
from .Pregunta import *
from .SecretariaPP import *"""