# Generated by Django 3.0.2 on 2020-02-11 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EsegJNE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField()),
                ('dni_responsable', models.CharField(blank=True, default='', max_length=45)),
                ('apellidos', models.CharField(blank=True, default='', max_length=100)),
                ('nombres', models.CharField(blank=True, default='', max_length=100)),
                ('sugerencia', models.CharField(blank=True, default='', max_length=400)),
                ('observacion', models.CharField(blank=True, default='', max_length=400)),
                ('fecha_registro', models.DateField()),
                ('usuario_registro', models.CharField(blank=True, default='', max_length=45)),
                ('fecha_modificacion', models.DateField()),
                ('usuario_modificacion', models.CharField(blank=True, default='', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, default='', max_length=45)),
                ('responsable', models.CharField(blank=True, default='', max_length=45)),
                ('fecha_registro', models.DateField()),
                ('usuario_registro', models.CharField(blank=True, default='', max_length=45)),
                ('fecha_modificacion', models.DateField()),
                ('usuario_modificacion', models.CharField(blank=True, default='', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Militante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(blank=True, default='', max_length=15)),
                ('apellidos', models.CharField(blank=True, default='', max_length=100)),
                ('nombres', models.CharField(blank=True, default='', max_length=100)),
                ('perfil', models.CharField(blank=True, default='', max_length=45)),
                ('cargo', models.CharField(blank=True, default='', max_length=45)),
                ('fecha_registro', models.DateField()),
                ('usuario_registro', models.CharField(blank=True, default='', max_length=45)),
                ('fecha_modificacion', models.DateField()),
                ('usuario_modificacion', models.CharField(blank=True, default='', max_length=45)),
                ('id_militante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Militante')),
            ],
        ),
        migrations.CreateModel(
            name='PartidoPolitico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', max_length=45)),
                ('estado', models.CharField(blank=True, default='', max_length=45)),
                ('fecha_registro', models.DateField()),
                ('usuario_registro', models.CharField(blank=True, default='', max_length=45)),
                ('fecha_modificacion', models.DateField()),
                ('usuario_modificacion', models.CharField(blank=True, default='', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(blank=True, default='', max_length=600)),
                ('fecha_registro', models.DateField()),
                ('usuario_registro', models.CharField(blank=True, default='', max_length=45)),
                ('fecha_modificacion', models.DateField()),
                ('usuario_modificacion', models.CharField(blank=True, default='', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, default='', max_length=45)),
                ('contra', models.CharField(blank=True, default='', max_length=45)),
                ('fecha_registro', models.DateField()),
                ('usuario_registro', models.CharField(blank=True, default='', max_length=45)),
                ('fecha_modificacion', models.DateField()),
                ('usuario_modificacion', models.CharField(blank=True, default='', max_length=45)),
                ('id_militante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Militante')),
            ],
        ),
        migrations.CreateModel(
            name='SecretariaPP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', max_length=45)),
                ('descripcion', models.CharField(blank=True, default='', max_length=200)),
                ('responsable', models.CharField(blank=True, default='', max_length=45)),
                ('fecha_registro', models.DateField()),
                ('usuario_registro', models.CharField(blank=True, default='', max_length=45)),
                ('fecha_modificacion', models.DateField()),
                ('usuario_modificacion', models.CharField(blank=True, default='', max_length=45)),
                ('id_partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PartidoPolitico')),
            ],
        ),
        migrations.CreateModel(
            name='PlanEstudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', max_length=100)),
                ('estado', models.CharField(blank=True, default='', max_length=45)),
                ('fecha_registro', models.DateField()),
                ('usuario_registro', models.CharField(blank=True, default='', max_length=45)),
                ('fecha_modificacion', models.DateField()),
                ('usuario_modificacion', models.CharField(blank=True, default='', max_length=45)),
                ('id_seg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.EsegJNE')),
            ],
        ),
        migrations.CreateModel(
            name='MilitanteExamen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField()),
                ('fecha_registro', models.DateField()),
                ('usuario_registro', models.CharField(blank=True, default='', max_length=45)),
                ('fecha_modificacion', models.DateField()),
                ('usuario_modificacion', models.CharField(blank=True, default='', max_length=45)),
                ('id_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Examen')),
                ('id_militante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Militante')),
            ],
        ),
        migrations.AddField(
            model_name='militante',
            name='id_partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PartidoPolitico'),
        ),
        migrations.AddField(
            model_name='militante',
            name='id_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PlanEstudio'),
        ),
        migrations.CreateModel(
            name='ExamenPregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField()),
                ('usuario_registro', models.CharField(blank=True, default='', max_length=45)),
                ('fecha_modificacion', models.DateField()),
                ('usuario_modificacion', models.CharField(blank=True, default='', max_length=45)),
                ('id_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Examen')),
                ('id_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Debate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(blank=True, default='', max_length=45)),
                ('estado', models.CharField(blank=True, default='', max_length=45)),
                ('moderador', models.CharField(blank=True, default='', max_length=45)),
                ('fecha_registro', models.DateField()),
                ('usuario_registro', models.CharField(blank=True, default='', max_length=45)),
                ('fecha_modificacion', models.DateField()),
                ('usuario_modificacion', models.CharField(blank=True, default='', max_length=45)),
                ('id_militante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Militante')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(blank=True, default='', max_length=45)),
                ('sumilla', models.CharField(blank=True, default='', max_length=300)),
                ('docente', models.CharField(blank=True, default='', max_length=100)),
                ('fecha_registro', models.DateField()),
                ('usuario_registro', models.CharField(blank=True, default='', max_length=45)),
                ('fecha_modificacion', models.DateField()),
                ('usuario_modificacion', models.CharField(blank=True, default='', max_length=45)),
                ('id_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PlanEstudio')),
            ],
        ),
        migrations.CreateModel(
            name='Conferencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(blank=True, default='', max_length=45)),
                ('apellidos_conferencista', models.CharField(blank=True, default='', max_length=100)),
                ('nombres_conferecista', models.CharField(blank=True, default='', max_length=100)),
                ('tipo', models.CharField(blank=True, default='', max_length=45)),
                ('fecha_registro', models.DateField()),
                ('usuario_registro', models.CharField(blank=True, default='', max_length=45)),
                ('fecha_modificacion', models.DateField()),
                ('usuario_modificacion', models.CharField(blank=True, default='', max_length=45)),
                ('id_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PlanEstudio')),
            ],
        ),
    ]
