# Generated by Django 3.0.4 on 2020-05-03 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='EsegJNE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField()),
                ('dni_responsable', models.CharField(blank=True, default='', max_length=45)),
                ('apellidos', models.CharField(blank=True, default='', max_length=100)),
                ('nombres', models.CharField(blank=True, default='', max_length=100)),
                ('sugerencia', models.CharField(blank=True, default='', max_length=400)),
                ('observacion', models.CharField(blank=True, default='', max_length=400)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('usuario_registro', models.CharField(blank=True, default='', max_length=45)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('usuario_modificacion', models.CharField(blank=True, default='', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, default='', max_length=45)),
                ('responsable', models.CharField(blank=True, default='', max_length=45)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('usuario_registro', models.CharField(blank=True, default='', max_length=45)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('usuario_modificacion', models.CharField(blank=True, default='', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Militante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.CharField(blank=True, default='', max_length=45)),
                ('cargo', models.CharField(blank=True, default='', max_length=45)),
                ('encargado', models.CharField(blank=True, default='', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='PartidoPolitico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', max_length=45)),
                ('estado', models.CharField(blank=True, default='', max_length=45)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('usuario_registro', models.CharField(blank=True, default='', max_length=45)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('usuario_modificacion', models.CharField(blank=True, default='', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(blank=True, default='', max_length=600)),
                ('puntaje', models.IntegerField()),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('usuario_registro', models.CharField(blank=True, default='', max_length=45)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('usuario_modificacion', models.CharField(blank=True, default='', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='SecretariaPP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', max_length=45)),
                ('descripcion', models.CharField(blank=True, default='', max_length=200)),
                ('responsable', models.CharField(blank=True, default='', max_length=45)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('usuario_registro', models.CharField(blank=True, default='', max_length=45)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('usuario_modificacion', models.CharField(blank=True, default='', max_length=45)),
                ('id_partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PartidoPolitico')),
            ],
        ),
        migrations.CreateModel(
            name='PlanEstudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', max_length=100)),
                ('estado', models.CharField(blank=True, default='', max_length=45)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('usuario_registro', models.CharField(blank=True, default='', max_length=45)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('usuario_modificacion', models.CharField(blank=True, default='', max_length=45)),
                ('id_seg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.EsegJNE')),
            ],
        ),
        migrations.CreateModel(
            name='MilitanteExamen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField()),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('usuario_registro', models.CharField(blank=True, default='', max_length=45)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('usuario_modificacion', models.CharField(blank=True, default='', max_length=45)),
                ('id_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Examen')),
                ('id_militante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Militante')),
            ],
        ),
        migrations.AddField(
            model_name='militante',
            name='id_partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PartidoPolitico'),
        ),
        migrations.AddField(
            model_name='militante',
            name='id_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PlanEstudio'),
        ),
        migrations.AddField(
            model_name='militante',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuario'),
        ),
        migrations.CreateModel(
            name='Externo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, default='', max_length=400)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ExamenPregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('usuario_registro', models.CharField(blank=True, default='', max_length=45)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('usuario_modificacion', models.CharField(blank=True, default='', max_length=45)),
                ('id_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Examen')),
                ('id_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Debate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(blank=True, default='', max_length=45)),
                ('estado', models.CharField(blank=True, default='', max_length=45)),
                ('moderador', models.CharField(blank=True, default='', max_length=45)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('usuario_registro', models.CharField(blank=True, default='', max_length=45)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('usuario_modificacion', models.CharField(blank=True, default='', max_length=45)),
                ('id_militante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Militante')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(blank=True, default='', max_length=45)),
                ('sumilla', models.CharField(blank=True, default='', max_length=300)),
                ('docente', models.CharField(blank=True, default='', max_length=100)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('usuario_registro', models.CharField(blank=True, default='', max_length=45)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('usuario_modificacion', models.CharField(blank=True, default='', max_length=45)),
                ('id_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PlanEstudio')),
            ],
        ),
        migrations.CreateModel(
            name='Conferencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(blank=True, default='', max_length=45)),
                ('apellidos_conferencista', models.CharField(blank=True, default='', max_length=100)),
                ('nombres_conferecista', models.CharField(blank=True, default='', max_length=100)),
                ('tipo', models.CharField(blank=True, default='', max_length=45)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('usuario_registro', models.CharField(blank=True, default='', max_length=45)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('usuario_modificacion', models.CharField(blank=True, default='', max_length=45)),
                ('id_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PlanEstudio')),
            ],
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('usuario_registro', models.CharField(blank=True, default='', max_length=45)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('usuario_modificacion', models.CharField(blank=True, default='', max_length=45)),
                ('contenido', models.CharField(blank=True, default='', max_length=45)),
                ('respuesta', models.BooleanField(default=False)),
                ('id_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Examen')),
            ],
            options={
                'ordering': ['-fecha_registro', '-fecha_modificacion'],
                'get_latest_by': 'fecha_registro',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(blank=True, default='', max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuario')),
            ],
        ),
    ]
