# Generated by Django 3.0.4 on 2020-04-23 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EsegJNE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField()),
                ('dni_responsable', models.CharField(blank=True, default='', max_length=45)),
                ('apellidos', models.CharField(blank=True, default='', max_length=100)),
                ('nombres', models.CharField(blank=True, default='', max_length=100)),
                ('sugerencia', models.CharField(blank=True, default='', max_length=400)),
                ('observacion', models.CharField(blank=True, default='', max_length=400)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('usuario_registro', models.CharField(blank=True, default='', max_length=45)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('usuario_modificacion', models.CharField(blank=True, default='', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, default='', max_length=45)),
                ('responsable', models.CharField(blank=True, default='', max_length=45)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('usuario_registro', models.CharField(blank=True, default='', max_length=45)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('usuario_modificacion', models.CharField(blank=True, default='', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='PartidoPolitico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', max_length=45)),
                ('estado', models.CharField(blank=True, default='', max_length=45)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('usuario_registro', models.CharField(blank=True, default='', max_length=45)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('usuario_modificacion', models.CharField(blank=True, default='', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(blank=True, max_length=40)),
                ('apellido_paterno', models.CharField(blank=True, default='nombre', max_length=20)),
                ('apellido_materno', models.CharField(blank=True, default='appellido_p', max_length=20)),
                ('dni', models.CharField(blank=True, default='apellido_m', max_length=15)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('usuario_registro', models.CharField(blank=True, default='user', max_length=45)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('usuario_modificacion', models.CharField(blank=True, default='user', max_length=45)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(blank=True, default='', max_length=600)),
                ('puntaje', models.IntegerField()),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('usuario_registro', models.CharField(blank=True, default='', max_length=45)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('usuario_modificacion', models.CharField(blank=True, default='', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Persona')),
                ('cargo', models.CharField(blank=True, default='', max_length=20)),
            ],
            bases=('api.persona',),
        ),
        migrations.CreateModel(
            name='Externo',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Persona')),
                ('descripcion', models.CharField(blank=True, default='', max_length=400)),
            ],
            bases=('api.persona',),
        ),
        migrations.CreateModel(
            name='Militante',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Persona')),
                ('perfil', models.CharField(blank=True, default='', max_length=45)),
                ('cargo', models.CharField(blank=True, default='', max_length=45)),
                ('encargado', models.CharField(blank=True, default='', max_length=45)),
                ('id_partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PartidoPolitico')),
            ],
            bases=('api.persona',),
        ),
        migrations.CreateModel(
            name='SecretariaPP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', max_length=45)),
                ('descripcion', models.CharField(blank=True, default='', max_length=200)),
                ('responsable', models.CharField(blank=True, default='', max_length=45)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('usuario_registro', models.CharField(blank=True, default='', max_length=45)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('usuario_modificacion', models.CharField(blank=True, default='', max_length=45)),
                ('id_partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PartidoPolitico')),
            ],
        ),
        migrations.CreateModel(
            name='PlanEstudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', max_length=100)),
                ('estado', models.CharField(blank=True, default='', max_length=45)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('usuario_registro', models.CharField(blank=True, default='', max_length=45)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('usuario_modificacion', models.CharField(blank=True, default='', max_length=45)),
                ('id_seg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.EsegJNE')),
            ],
        ),
        migrations.CreateModel(
            name='ExamenPregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('usuario_registro', models.CharField(blank=True, default='', max_length=45)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('usuario_modificacion', models.CharField(blank=True, default='', max_length=45)),
                ('id_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Examen')),
                ('id_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(blank=True, default='', max_length=45)),
                ('sumilla', models.CharField(blank=True, default='', max_length=300)),
                ('docente', models.CharField(blank=True, default='', max_length=100)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('usuario_registro', models.CharField(blank=True, default='', max_length=45)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('usuario_modificacion', models.CharField(blank=True, default='', max_length=45)),
                ('id_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PlanEstudio')),
            ],
        ),
        migrations.CreateModel(
            name='Conferencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(blank=True, default='', max_length=45)),
                ('apellidos_conferencista', models.CharField(blank=True, default='', max_length=100)),
                ('nombres_conferecista', models.CharField(blank=True, default='', max_length=100)),
                ('tipo', models.CharField(blank=True, default='', max_length=45)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('usuario_registro', models.CharField(blank=True, default='', max_length=45)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('usuario_modificacion', models.CharField(blank=True, default='', max_length=45)),
                ('id_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PlanEstudio')),
            ],
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(blank=True, default='', max_length=45)),
                ('respuesta', models.BooleanField(default=False)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('usuario_registro', models.CharField(blank=True, default='', max_length=45)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('usuario_modificacion', models.CharField(blank=True, default='', max_length=45)),
                ('id_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Examen')),
            ],
        ),
        migrations.CreateModel(
            name='MilitanteExamen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField()),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('usuario_registro', models.CharField(blank=True, default='', max_length=45)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('usuario_modificacion', models.CharField(blank=True, default='', max_length=45)),
                ('id_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Examen')),
                ('id_militante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Militante')),
            ],
        ),
        migrations.AddField(
            model_name='militante',
            name='id_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PlanEstudio'),
        ),
        migrations.CreateModel(
            name='Debate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(blank=True, default='', max_length=45)),
                ('estado', models.CharField(blank=True, default='', max_length=45)),
                ('moderador', models.CharField(blank=True, default='', max_length=45)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('usuario_registro', models.CharField(blank=True, default='', max_length=45)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('usuario_modificacion', models.CharField(blank=True, default='', max_length=45)),
                ('id_militante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Militante')),
            ],
        ),
    ]
